### ISSUE TITLE
done

### ISSUE THREAD

**Issue by powerlord1990** [powerlord1990/HW4.1.MegaFUU#5]

**Comment by powerlord1990** [comment]
я опять не совсем правильно по-моему ишью закрыл. я добавил id. а год я принимаю за 365 дней по причине опыта работы в мегафоне. там год всегда указывали за 365 дней. так же принятие такого значения позволит нам описать некоторые тарифы (например твой безлимит на 6 месяцев можно установить как Tariff.year/2)

**Comment by coursar** [comment]
Закрывайте правильно
